const hz=m=>440*2**((m-69)/12);
export class AudioDirector{
  constructor(){this.ctx=null;this.master=null;this.music=null;this.sfxBus=null;this.enabled=true;this.timer=null;this.world=null;this.step=0;this.danger=0;}
  async unlock(){if(!this.enabled)return;if(!this.ctx){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;this.ctx=new C();this.master=this.ctx.createGain();this.music=this.ctx.createGain();this.sfxBus=this.ctx.createGain();const comp=this.ctx.createDynamicsCompressor();this.master.gain.value=.48;this.music.gain.value=.18;this.sfxBus.gain.value=.5;this.music.connect(this.master);this.sfxBus.connect(this.master);this.master.connect(comp);comp.connect(this.ctx.destination);}if(this.ctx.state==='suspended')await this.ctx.resume();}
  setEnabled(v){this.enabled=v;if(this.master&&this.ctx)this.master.gain.setTargetAtTime(v?.48:0,this.ctx.currentTime,.03);if(!v)this.stopMusic();else if(this.world)this.startMusic(this.world);}
  setDanger(v){this.danger=Math.max(0,Math.min(1,v));}
  tone(freq,d=.1,type='sine',gain=.08,when=0,slide=0,bus='sfx'){if(!this.ctx||!this.enabled)return;const t=this.ctx.currentTime+when,o=this.ctx.createOscillator(),a=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(20,freq+slide),t+d);a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(gain,t+.006);a.gain.exponentialRampToValueAtTime(.0001,t+d+.08);o.connect(a);a.connect(bus==='music'?this.music:this.sfxBus);o.start(t);o.stop(t+d+.1);}
  noise(d=.08,g=.035,filter=800){if(!this.ctx||!this.enabled)return;const n=Math.floor(this.ctx.sampleRate*d),b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),data=b.getChannelData(0);for(let i=0;i<n;i++)data[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),a=this.ctx.createGain();s.buffer=b;f.type='bandpass';f.frequency.value=filter;a.gain.value=g;s.connect(f);f.connect(a);a.connect(this.sfxBus);s.start();}
  sfx(name){const bank={move:()=>this.tone(165,.04,'triangle',.04,0,22),bump:()=>{this.tone(85,.07,'square',.06,0,-18);this.noise(.05,.025,500)},spark:()=>[660,880,1100].forEach((f,i)=>this.tone(f,.12,'sine',.09,i*.045,80)),key:()=>[523,784].forEach((f,i)=>this.tone(f,.16,'triangle',.09,i*.06)),unlock:()=>[220,330,494].forEach((f,i)=>this.tone(f,.16,'sawtooth',.055,i*.055,35)),push:()=>{this.tone(105,.09,'square',.07,0,-18);this.noise(.08,.03,720)},teleport:()=>[240,370,500,720].forEach((f,i)=>this.tone(f,.12,'sine',.07,i*.025,160)),undo:()=>[520,390,290].forEach((f,i)=>this.tone(f,.08,'triangle',.05,i*.03)),danger:()=>{this.tone(76,.22,'sawtooth',.12,0,-20);this.noise(.18,.05,400)},win:()=>[60,64,67,72,76].forEach((m,i)=>this.tone(hz(m),.24,i<3?'triangle':'sine',.1,i*.08,24)),click:()=>this.tone(420,.045,'square',.045,0,35),page:()=>{this.noise(.14,.025,1800);this.tone(310,.08,'triangle',.04)}};bank[name]?.();}
  startMusic(world){this.world=world;if(!this.ctx||!this.enabled)return;this.stopMusic();this.step=0;const beat=60/world.music.tempo/2;const tick=()=>{if(!this.ctx||!this.enabled||!this.world)return;const s=this.step++,{root,scale}=this.world.music;const degree=scale[(s*3+(s>>2))%scale.length];if(s%2===0)this.tone(hz(root-12+(s%8===0?0:7)),beat*.72,'triangle',.04,0,0,'music');if([0,3,6].includes(s%8))this.tone(hz(root+degree),beat*.55,'square',.022+.018*this.danger,0,0,'music');if(s%8===4)this.tone(hz(root+12+scale[(s>>1)%scale.length]),beat*1.4,'sine',.024,0,0,'music');if(this.danger>.55&&s%2===1)this.tone(hz(root-5),beat*.18,'sawtooth',.015,0,0,'music');};tick();this.timer=setInterval(tick,beat*1000);}
  stopMusic(){if(this.timer){clearInterval(this.timer);this.timer=null;}}
}
