import {LEVELS,WORLDS,TILE,GRID_W,GRID_H,getLevel} from './levels.js';
import {AudioDirector} from './audio.js';
import {VIEW,background,panel,button,text,wrap,drawTile,drawSpark,drawKey,drawCrate,drawPip,drawEnemy,logo,comic} from './art.js';

const canvas=document.getElementById('game');const ctx=canvas.getContext('2d');const live=document.getElementById('live-region');
const audio=new AudioDirector();
const SAVE_KEY='pip-prism-vault-save-v1';
const DEFAULT_SAVE={unlocked:1,completed:{},stars:{},best:{},sound:true,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,contrast:false,introSeen:false};
let save=loadSave();audio.enabled=save.sound;
let screen='title',comicPage=0,selectedWorld=0,selectedLevel=0,hover=-1,lastTime=0,time=0,shake=0,flash=0,particles=[],buttons=[];
let game=null;

function loadSave(){try{return {...DEFAULT_SAVE,...JSON.parse(localStorage.getItem(SAVE_KEY)||'{}')}}catch{return {...DEFAULT_SAVE}}}
function persist(){localStorage.setItem(SAVE_KEY,JSON.stringify(save));}
function announce(s){live.textContent='';setTimeout(()=>live.textContent=s,10)}
function clone(v){return structuredClone(v)}
function tileAt(x,y){return game.level.tiles[y]?.[x]??TILE.WALL}
function enemyAt(x,y){return game.enemies.find(e=>e.x===x&&e.y===y)}
function crateAt(x,y){return game.crates.find(c=>c.x===x&&c.y===y)}
function pressed(){return game.crates.some(c=>tileAt(c.x,c.y)===TILE.PLATE)||tileAt(game.player.x,game.player.y)===TILE.PLATE}
function exitActive(){return game.sparks.length===0}
function pushHistory(){game.history.push(clone({player:game.player,crates:game.crates,enemies:game.enemies,sparks:game.sparks,keys:game.keys,inventory:game.inventory,moves:game.moves,turn:game.turn,tiles:game.level.tiles,dead:game.dead}));if(game.history.length>80)game.history.shift()}
function restore(s){Object.assign(game,clone(s));game.anim={from:{...game.player},to:{...game.player},start:time,duration:1};game.dead=false;audio.sfx('undo')}
function loadLevel(id){const src=getLevel(id);game={level:clone(src),player:{...src.start,dir:1},crates:clone(src.crates),enemies:clone(src.enemies),sparks:clone(src.sparks),keys:clone(src.keys),inventory:{keys:0},moves:0,turn:0,history:[],dead:false,won:false,hint:false,anim:null,locked:false};screen='play';selectedLevel=id-1;audio.startMusic(WORLDS[src.world-1]);announce(`Room ${id}, ${src.name}`)}
function addBurst(x,y,color,count=18){for(let i=0;i<count;i++){const a=Math.random()*Math.PI*2,s=1.2+Math.random()*4;particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-1,life:650+Math.random()*350,max:1000,color,size:2+Math.random()*5})}}
function boardPos(x,y){return {x:VIEW.boardX+x*VIEW.tile+VIEW.tile/2,y:VIEW.boardY+y*VIEW.tile+VIEW.tile/2}}
function walkable(x,y,forEnemy=false,ghost=false){const t=tileAt(x,y);if(!ghost&&t===TILE.WALL)return false;if([TILE.WATER,TILE.PIT].includes(t)&&!forEnemy)return false;if(t===TILE.DOOR)return game.inventory.keys>0;if(t===TILE.GATE&&!pressed())return false;if(crateAt(x,y))return false;return x>0&&y>0&&x<GRID_W-1&&y<GRID_H-1}
function step(dx,dy,auto=false){if(screen!=='play'||game.dead||game.won||game.locked)return false;const from={...game.player};let nx=from.x+dx,ny=from.y+dy;const crate=crateAt(nx,ny);if(crate){const bx=nx+dx,by=ny+dy;if(!walkable(bx,by)||enemyAt(bx,by)){audio.sfx('bump');return false}if(!auto)pushHistory();crate.x=bx;crate.y=by;audio.sfx('push')}else{if(!walkable(nx,ny)){if(tileAt(nx,ny)===TILE.DOOR&&game.inventory.keys>0){if(!auto)pushHistory();game.inventory.keys--;game.level.tiles[ny][nx]=TILE.FLOOR;audio.sfx('unlock')}else{audio.sfx('bump');return false}}else if(!auto)pushHistory()}
if(enemyAt(nx,ny)){defeat();return false}game.player.x=nx;game.player.y=ny;game.player.dir=dx?Math.sign(dx):game.player.dir;if(!auto){game.moves++;game.turn++;}game.anim={from,to:{...game.player},start:time,duration:save.reduced?1:125};audio.sfx('move');resolveCell(from);if(!auto&&!game.dead&&!game.won){moveEnemies(dx,dy);checkEnemyCollision();updateDanger()}return true}
function resolveCell(from){const p=game.player,t=tileAt(p.x,p.y);const si=game.sparks.findIndex(s=>s.x===p.x&&s.y===p.y);if(si>=0){game.sparks.splice(si,1);const q=boardPos(p.x,p.y);addBurst(q.x,q.y,'#ffe86d',24);audio.sfx('spark');announce(`${3-game.sparks.length} of 3 Sparks collected`)}const ki=game.keys.findIndex(k=>k.x===p.x&&k.y===p.y);if(ki>=0){game.keys.splice(ki,1);game.inventory.keys++;audio.sfx('key');announce('Sunkey collected')}
if(tileAt(from.x,from.y)===TILE.FRAGILE)game.level.tiles[from.y][from.x]=TILE.PIT;
if(t===TILE.SPIKE||t===TILE.WATER||t===TILE.PIT){defeat();return}
if(t===TILE.TELEPORT_A||t===TILE.TELEPORT_B){const other=t===TILE.TELEPORT_A?TILE.TELEPORT_B:TILE.TELEPORT_A;outer:for(let y=1;y<GRID_H-1;y++)for(let x=1;x<GRID_W-1;x++)if(tileAt(x,y)===other&&!crateAt(x,y)){const a=boardPos(p.x,p.y);addBurst(a.x,a.y,t===TILE.TELEPORT_A?'#67f3ff':'#ff69c0',16);p.x=x;p.y=y;const b=boardPos(x,y);addBurst(b.x,b.y,other===TILE.TELEPORT_A?'#67f3ff':'#ff69c0',16);audio.sfx('teleport');break outer}}
if(t===TILE.CONVEYOR_R)setTimeout(()=>step(1,0,true),save.reduced?0:90);if(t===TILE.CONVEYOR_L)setTimeout(()=>step(-1,0,true),save.reduced?0:90);
if(t===TILE.ICE){const dx=p.x-from.x,dy=p.y-from.y;if(dx||dy)setTimeout(()=>step(dx,dy,true),save.reduced?0:80)}
if(t===TILE.EXIT&&exitActive())winRoom()}
function moveEnemies(lastDx,lastDy){for(const e of game.enemies){if(e.type==='turret'){if(game.turn%3===0&&lineOfSight(e,game.player)){defeat();return}continue}let dx=0,dy=0;const phase=(game.turn+e.phase)%2;if(e.type==='scarab'){dx=e.dir%2===0?1:-1}else if(e.type==='crawler'){dy=e.dir%2===0?1:-1}else if(e.type==='slime'&&phase===0){if(Math.abs(game.player.x-e.x)>=Math.abs(game.player.y-e.y))dx=Math.sign(game.player.x-e.x);else dy=Math.sign(game.player.y-e.y)}else if(e.type==='hopper'&&phase===0){dx=Math.sign(game.player.x-e.x)*2;if(Math.abs(game.player.y-e.y)>Math.abs(game.player.x-e.x)){dy=Math.sign(game.player.y-e.y)*2;dx=0}}else if(e.type==='ghost'&&phase===0){if(Math.abs(game.player.x-e.x)>=Math.abs(game.player.y-e.y))dx=Math.sign(game.player.x-e.x);else dy=Math.sign(game.player.y-e.y)}else if(e.type==='mimic'){dx=lastDx;dy=lastDy}else if(e.type==='drone'){const dirs=[[1,0],[0,1],[-1,0],[0,-1]],d=dirs[(game.turn+e.dir)%4];dx=d[0];dy=d[1]}
const nx=e.x+dx,ny=e.y+dy;const ghost=e.type==='ghost';if(dx||dy){if(walkable(nx,ny,true,ghost)&&!game.enemies.some(o=>o!==e&&o.x===nx&&o.y===ny)){e.x=nx;e.y=ny}else if(['scarab','crawler'].includes(e.type))e.dir=(e.dir+1)%2}}
}
function lineOfSight(a,b){if(a.x===b.x){const s=Math.sign(b.y-a.y);for(let y=a.y+s;y!==b.y;y+=s)if([TILE.WALL,TILE.DOOR].includes(tileAt(a.x,y)))return false;return true}if(a.y===b.y){const s=Math.sign(b.x-a.x);for(let x=a.x+s;x!==b.x;x+=s)if([TILE.WALL,TILE.DOOR].includes(tileAt(x,a.y)))return false;return true}return false}
function checkEnemyCollision(){if(game.enemies.some(e=>e.x===game.player.x&&e.y===game.player.y))defeat()}
function updateDanger(){let d=0;for(const e of game.enemies){const m=Math.abs(e.x-game.player.x)+Math.abs(e.y-game.player.y);if(m<4)d=Math.max(d,(4-m)/3);if(e.type==='turret'&&lineOfSight(e,game.player))d=Math.max(d,.75)}audio.setDanger(d)}
function defeat(){if(game.dead||game.won)return;game.dead=true;shake=18;flash=.7;audio.sfx('danger');screen='defeat';announce('Pip was caught. Undo or retry.')}
function starsFor(m,p){return m<=p?3:m<=Math.ceil(p*1.45)?2:1}
function winRoom(){if(game.won)return;game.won=true;const id=game.level.id,stars=starsFor(game.moves,game.level.par);save.completed[id]=true;save.stars[id]=Math.max(save.stars[id]||0,stars);save.best[id]=Math.min(save.best[id]||9999,game.moves);save.unlocked=Math.max(save.unlocked,Math.min(100,id+1));persist();const q=boardPos(game.player.x,game.player.y);addBurst(q.x,q.y,'#ffe86d',42);audio.sfx('win');screen=id===100?'ending':'victory';announce(`Room complete. ${stars} stars.`)}
function undo(){if((screen==='play'||screen==='defeat')&&game?.history.length){const s=game.history.pop();restore(s);screen='play'}}
function restart(){if(game)loadLevel(game.level.id)}
function menu(){screen='title';audio.stopMusic();}

function input(action){audio.unlock();if(action==='up')step(0,-1);if(action==='down')step(0,1);if(action==='left')step(-1,0);if(action==='right')step(1,0);if(action==='undo')undo();if(action==='restart')restart()}
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();input(b.dataset.action)}));
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' ','enter'].includes(k))e.preventDefault();audio.unlock();if(screen==='comic'){if(k==='enter'||k===' '){if(comicPage<1){comicPage++;audio.sfx('page')}else{save.introSeen=true;persist();screen='select'}}return}if(screen==='title'){if(k==='enter'||k===' '){screen=save.introSeen?'select':'comic';comicPage=0;audio.sfx('click')}return}if(k==='escape'||k==='p'){if(screen==='play')screen='pause';else if(screen==='pause')screen='play';else if(screen!=='title')menu();return}if(k==='m'){save.sound=!save.sound;audio.setEnabled(save.sound);persist();return}if(k==='f'){document.fullscreenElement?document.exitFullscreen():canvas.parentElement.requestFullscreen?.();return}if(k==='h'&&screen==='play'){game.hint=!game.hint;return}if(k==='z'||k==='backspace'){undo();return}if(k==='r'){restart();return}const map={arrowup:'up',w:'up',arrowdown:'down',s:'down',arrowleft:'left',a:'left',arrowright:'right',d:'right'};if(map[k])input(map[k]);});
canvas.addEventListener('pointermove',e=>{const p=pointer(e);hover=buttons.findIndex(b=>inside(p,b.r))});
canvas.addEventListener('pointerdown',e=>{audio.unlock();const p=pointer(e);const b=buttons.find(b=>inside(p,b.r));if(b){audio.sfx('click');b.fn();return}if(screen==='comic'){if(comicPage<1){comicPage++;audio.sfx('page')}else{save.introSeen=true;persist();screen='select'}}});
function pointer(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
function inside(p,r){return p.x>=r.x&&p.y>=r.y&&p.x<=r.x+r.w&&p.y<=r.y+r.h}
function addButton(r,label,fn,accent){const idx=buttons.length;buttons.push({r,label,fn});button(ctx,r,label,hover===idx,accent)}

function drawTitle(){background(ctx,WORLDS[0],time);ctx.save();ctx.globalAlpha=.3;for(let i=0;i<8;i++)drawSpark(ctx,115+i*150,90+(i%2)*25,34,time+i*90);ctx.restore();panel(ctx,160,95,960,530,'#ffe56d',.84);logo(ctx,640,235,1.35);drawPip(ctx,430,480,230,time,1,'idle');text(ctx,'100 single-screen puzzle rooms',745,390,30,'#fff4d6','center',900);text(ctx,'10 living galleries · 8 enemy families',745,430,22,'#bcefff','center',800);addButton({x:650,y:485,w:310,h:66},save.introSeen?'CONTINUE':'BEGIN STORY',()=>{screen=save.introSeen?'select':'comic';comicPage=0},'#ffe56d');addButton({x:650,y:565,w:145,h:48},'CREDITS',()=>screen='credits');addButton({x:815,y:565,w:145,h:48},'OPTIONS',()=>screen='options');}
function drawSelect(){background(ctx,WORLDS[selectedWorld],time);panel(ctx,34,28,1212,664,WORLDS[selectedWorld].color,.9);text(ctx,'CHAPTER DIRECTORY',70,70,32,'#fff4d6');text(ctx,`${Object.keys(save.completed).length} / 100 ROOMS RESTORED`,1210,70,19,'#bdefff','right');for(let w=0;w<10;w++){const r={x:68+(w%5)*228,y:100+Math.floor(w/5)*92,w:208,h:70};const locked=save.unlocked<(w*10+1);addButton(r,locked?`LOCKED ${w+1}`:`${w+1}. ${WORLDS[w].name.split(' ')[0].toUpperCase()}`,()=>{if(!locked){selectedWorld=w;selectedLevel=w*10}},WORLDS[w].color)}const world=WORLDS[selectedWorld];text(ctx,world.name,72,312,32,world.color);text(ctx,world.tagline,72,347,20,'#fff4d6');for(let i=0;i<10;i++){const id=selectedWorld*10+i+1,r={x:72+(i%5)*145,y:385+Math.floor(i/5)*92,w:128,h:70};const locked=id>save.unlocked;const stars=save.stars[id]||0;addButton(r,locked?'—':`${String(id).padStart(3,'0')}  ${'★'.repeat(stars)}`,()=>{if(!locked)loadLevel(id)},world.color)}wrap(ctx,world.brief,820,330,360,21,28,'#dceaff');addButton({x:1010,y:626,w:190,h:44},'BACK',menu);}
function drawHUD(){const w=WORLDS[game.level.world-1];panel(ctx,VIEW.hudX,42,VIEW.hudW,636,w.color,.92);text(ctx,`ROOM ${String(game.level.id).padStart(3,'0')}`,VIEW.hudX+28,78,20,w.color);wrap(ctx,game.level.name,VIEW.hudX+28,116,330,30,34,'#fff4d6');text(ctx,w.name,VIEW.hudX+28,163,17,'#bdefff');text(ctx,'SPARKS',VIEW.hudX+28,220,17,'#9fb4d8');text(ctx,`${3-game.sparks.length} / 3`,VIEW.hudX+342,220,30,'#ffe56d','right');text(ctx,'MOVES',VIEW.hudX+28,272,17,'#9fb4d8');text(ctx,String(game.moves),VIEW.hudX+342,272,30,'#fff4d6','right');text(ctx,'PAR',VIEW.hudX+28,318,17,'#9fb4d8');text(ctx,String(game.level.par),VIEW.hudX+342,318,25,'#dceaff','right');text(ctx,'SUNKEYS',VIEW.hudX+28,364,17,'#9fb4d8');text(ctx,String(game.inventory.keys),VIEW.hudX+342,364,25,'#ffe56d','right');text(ctx,'UNDO',VIEW.hudX+28,410,17,'#9fb4d8');text(ctx,String(game.history.length),VIEW.hudX+342,410,25,'#dceaff','right');if(game.hint){panel(ctx,VIEW.hudX+20,446,VIEW.hudW-40,106,w.color,.75);wrap(ctx,game.level.hint,VIEW.hudX+38,470,310,18,24,'#fff4d6')}else{text(ctx,'H',VIEW.hudX+42,488,20,w.color,'center');text(ctx,'show room insight',VIEW.hudX+75,488,18,'#b9c9e4')}addButton({x:VIEW.hudX+24,y:588,w:104,h:48},'UNDO',undo,w.color);addButton({x:VIEW.hudX+143,y:588,w:104,h:48},'RETRY',restart,w.color);addButton({x:VIEW.hudX+262,y:588,w:104,h:48},'PAUSE',()=>screen='pause',w.color)}
function drawPlay(){const w=WORLDS[game.level.world-1];background(ctx,w,time);ctx.save();if(shake)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);panel(ctx,28,110,790,558,w.color,.8);const plate=pressed();for(let y=0;y<GRID_H;y++)for(let x=0;x<GRID_W;x++)drawTile(ctx,tileAt(x,y),VIEW.boardX+x*VIEW.tile,VIEW.boardY+y*VIEW.tile,VIEW.tile,w,time,{active:exitActive(),on:plate,open:plate});for(const s of game.sparks){const p=boardPos(s.x,s.y);drawSpark(ctx,p.x,p.y,30,time)}for(const k of game.keys){const p=boardPos(k.x,k.y);drawKey(ctx,p.x,p.y,38)}for(const cr of game.crates){const p=boardPos(cr.x,cr.y);drawCrate(ctx,p.x,p.y,48,w)}for(const e of game.enemies){const p=boardPos(e.x,e.y);if(e.type==='turret'&&game.turn%3===2&&lineOfSight(e,game.player)){ctx.save();ctx.strokeStyle=w.danger;ctx.globalAlpha=.45;ctx.lineWidth=5;ctx.setLineDash([8,8]);ctx.beginPath();ctx.moveTo(p.x,p.y);const q=boardPos(game.player.x,game.player.y);ctx.lineTo(q.x,q.y);ctx.stroke();ctx.restore()}drawEnemy(ctx,e,p.x,p.y,50,time,w)}let pp=boardPos(game.player.x,game.player.y);if(game.anim&&time-game.anim.start<game.anim.duration){const a=(time-game.anim.start)/game.anim.duration,q=boardPos(game.anim.from.x,game.anim.from.y),r=boardPos(game.anim.to.x,game.anim.to.y);pp={x:q.x+(r.x-q.x)*a,y:q.y+(r.y-q.y)*a}}drawPip(ctx,pp.x,pp.y,54,time,game.player.dir,'move',save.contrast);for(const p of particles){ctx.save();ctx.globalAlpha=Math.max(0,p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore();drawHUD()}
function overlay(title,sub){ctx.fillStyle='rgba(4,7,18,.74)';ctx.fillRect(0,0,1280,720);panel(ctx,335,130,610,470,'#ffe56d',.97);text(ctx,title,640,205,48,'#fff4d6','center',1000);wrap(ctx,sub,640,258,510,21,29,'#cfeaff','center')}
function drawPause(){drawPlay();overlay('PAUSED','The Vault waits. Nothing moves until Pip does.');addButton({x:465,y:350,w:350,h:58},'RESUME',()=>screen='play','#67f3ff');addButton({x:465,y:424,w:350,h:52},'OPTIONS',()=>screen='options','#ffe56d');addButton({x:465,y:492,w:350,h:52},'CHAPTER DIRECTORY',()=>screen='select','#ff79aa')}
function drawDefeat(){drawPlay();overlay('THREAD BROKEN','Every mistake is information. Rewind one turn or reset the room.');if(game.history.length)addButton({x:455,y:360,w:370,h:60},'UNDO LAST TURN',undo,'#67f3ff');addButton({x:455,y:438,w:370,h:54},'RESTART ROOM',restart,'#ffe56d');addButton({x:455,y:508,w:370,h:50},'DIRECTORY',()=>screen='select','#ff7b9b')}
function drawVictory(){drawPlay();const stars=starsFor(game.moves,game.level.par);overlay('ROOM RESTORED',`${game.level.name} is bright again. ${game.moves} moves against par ${game.level.par}.`);text(ctx,'★'.repeat(stars)+'☆'.repeat(3-stars),640,330,58,'#ffe56d','center',1000);addButton({x:455,y:395,w:370,h:58},game.level.id===100?'SEE THE ENDING':'NEXT ROOM',()=>game.level.id===100?screen='ending':loadLevel(game.level.id+1),'#ffe56d');addButton({x:455,y:470,w:370,h:50},'REPLAY',restart,'#67f3ff');addButton({x:455,y:535,w:370,h:46},'DIRECTORY',()=>screen='select','#ff7aa0')}
function drawOptions(){background(ctx,WORLDS[selectedWorld]||WORLDS[0],time);panel(ctx,330,80,620,560,'#67f3ff');text(ctx,'OPTIONS',640,140,44,'#fff4d6','center',1000);const toggle=(y,label,val,fn)=>{text(ctx,label,410,y+27,24,'#fff4d6');addButton({x:690,y,w:180,h:54},val?'ON':'OFF',fn,val?'#67f3ff':'#ff7b9b')};toggle(210,'SOUND',save.sound,()=>{save.sound=!save.sound;audio.setEnabled(save.sound);persist()});toggle(290,'REDUCED MOTION',save.reduced,()=>{save.reduced=!save.reduced;persist()});toggle(370,'HIGH CONTRAST',save.contrast,()=>{save.contrast=!save.contrast;persist()});addButton({x:455,y:475,w:370,h:58},'FULLSCREEN',()=>document.fullscreenElement?document.exitFullscreen():canvas.parentElement.requestFullscreen?.(),'#ffe56d');addButton({x:455,y:552,w:370,h:48},'BACK',()=>screen=game&&game.level?'pause':'title','#67f3ff')}
function drawCredits(){background(ctx,WORLDS[6],time);panel(ctx,170,55,940,610,'#dbe3ff');logo(ctx,640,140,.8);text(ctx,'ORIGINAL GAME, ART SYSTEM, LEVEL SYSTEM, MUSIC & SFX',640,260,19,'#dceaff','center');text(ctx,'ALEX DE VRIES XING · PIP’S POCKET WORLDS',640,305,27,'#ffe56d','center',1000);wrap(ctx,'Built as a dependency-free Canvas 2D production first pass. Every runtime visual and sound is generated from original code and editable vector assets in the repository.',640,365,720,22,31,'#fff4d6','center');text(ctx,'Thank you for keeping the light.',640,505,25,'#bdefff','center');addButton({x:515,y:570,w:250,h:52},'BACK',menu,'#ffe56d')}
function drawEnding(){background(ctx,WORLDS[9],time);for(let i=0;i<10;i++)drawSpark(ctx,110+i*118,120+Math.sin(i+time*.002)*30,50,time+i*70);panel(ctx,190,120,900,500,'#ffe56d',.85);logo(ctx,640,220,.9);text(ctx,'MORNING RETURNS',640,345,48,'#fff4d6','center',1000);wrap(ctx,'The Prism Heart sings. Every pocket world wakes. Far beyond the restored Vault, a clockwork moon blinks once in the dark…',640,410,700,24,34,'#dceaff','center');addButton({x:470,y:530,w:340,h:58},'CHAPTER DIRECTORY',()=>screen='select','#ffe56d');addButton({x:550,y:605,w:180,h:42},'CREDITS',()=>screen='credits','#67f3ff')}

function update(dt){for(const p of particles){p.x+=p.vx*dt*.06;p.y+=p.vy*dt*.06;p.vy+=.006*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);shake=Math.max(0,shake-dt*.04);flash=Math.max(0,flash-dt*.002)}
function render(ts){const dt=Math.min(40,ts-lastTime||16);lastTime=ts;time=ts;buttons=[];update(dt);hover=-1;if(screen==='title')drawTitle();else if(screen==='comic')comic(ctx,comicPage,time);else if(screen==='select')drawSelect();else if(screen==='play')drawPlay();else if(screen==='pause')drawPause();else if(screen==='defeat')drawDefeat();else if(screen==='victory')drawVictory();else if(screen==='options')drawOptions();else if(screen==='credits')drawCredits();else if(screen==='ending')drawEnding();if(flash){ctx.fillStyle=`rgba(255,255,255,${flash})`;ctx.fillRect(0,0,1280,720)}requestAnimationFrame(render)}
requestAnimationFrame(render);
